# Generated by Django 3.0.8 on 2020-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useranswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wish_gender',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Femme', max_length=10),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='q1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='s1',
            field=models.PositiveIntegerField(),
        ),
    ]
