# Generated by Django 3.0.8 on 2020-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200723_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='q1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='s1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Homme', 'Un homme'), ('Femme', 'Une femme')], default='Homme', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wish_gender',
            field=models.CharField(choices=[('Homme', 'Un homme'), ('Femme', 'Une femme')], default='Femme', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
