# Generated by Django 3.0.8 on 2020-08-22 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200822_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='s1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
