# Generated by Django 3.0.8 on 2020-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_avatars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatars',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default="Pas d'image selectionnee", max_length=10),
        ),
    ]
